tacticrafter:
  critic_mode: auto
  negotiator_model_name: openrouter-deepseek/deepseek-chat
  negotiator_temperature: 0.3
  causal_model_name: openrouter-deepseek/deepseek-chat
  causal_temperature: 0.3
  opponent_model_name: openrouter-deepseek/deepseek-chat
  opponent_temperature: 0.3
  voyager_options:
    action_agent_task_max_retries: 10
    action_agent_show_chat_log: true
    action_agent_temperature: 0.3
    action_agent_model_name: openrouter-deepseek/deepseek-chat
    critic_agent_model_name: openrouter-deepseek/deepseek-chat
