tacticrafter:
  critic_mode: auto
  negotiator_model_name: ollama-qwen2.5:14b
  negotiator_temperature: 0.3
  causal_model_name: ollama-qwen2.5:14b
  causal_temperature: 0.3
  opponent_model_name: ollama-qwen2.5:14b
  opponent_temperature: 0.3
  voyager_options:
    action_agent_task_max_retries: 50
    action_agent_show_chat_log: true
    action_agent_temperature: 0.3
    action_agent_model_name: ollama-qwen2.5:14b
    critic_agent_model_name: ollama-qwen2.5:14b
