defaults:
  - _self_
  - agents:
    - tacticrafter

mc_port: 49172
server_port: 3000
env_wait_ticks: 80

scenarios:
#   E
  - name: Dash and Dine
    agent: dash_and_dine_berries
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_berries
    opponents: [dash_and_dine_berries]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_berries
    opponents: [dash_and_dine_cake_beetroot]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_berries
    opponents: [dash_and_dine_melon_pumpkin]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_berries
    opponents: [dash_and_dine_potato_cookie]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: dash_and_dine_cake_beetroot
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_cake_beetroot
    opponents: [dash_and_dine_berries]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_cake_beetroot
    opponents: [dash_and_dine_cake_beetroot]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_cake_beetroot
    opponents: [dash_and_dine_melon_pumpkin]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_cake_beetroot
    opponents: [dash_and_dine_potato_cookie]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: dash_and_dine_melon_pumpkin
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_melon_pumpkin
    opponents: [dash_and_dine_berries]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_melon_pumpkin
    opponents: [dash_and_dine_cake_beetroot]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_melon_pumpkin
    opponents: [dash_and_dine_melon_pumpkin]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_melon_pumpkin
    opponents: [dash_and_dine_potato_cookie]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: dash_and_dine_potato_cookie
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_potato_cookie
    opponents: [dash_and_dine_berries]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_potato_cookie
    opponents: [dash_and_dine_cake_beetroot]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_potato_cookie
    opponents: [dash_and_dine_melon_pumpkin]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: dash_and_dine_potato_cookie
    opponents: [dash_and_dine_potato_cookie]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: do_nothing
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: do_nothing
    opponents: [dash_and_dine_berries]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: do_nothing
    opponents: [dash_and_dine_cake_beetroot]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: do_nothing
    opponents: [dash_and_dine_melon_pumpkin]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Dash and Dine
    agent: do_nothing
    opponents: [dash_and_dine_potato_cookie]
    num_episodes: 20
    kwargs:
      episode_timeout: 120


hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}