defaults:
  - _self_
  - agents:
    - tacticrafter

mc_port: 49172
server_port: 3000
env_wait_ticks: 80

scenarios:
#   E
  - name: Mushroom War
    agent: do_nothing
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: do_nothing
    opponents: [mushroom_war_aggressive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: do_nothing
    opponents: [mushroom_war_balanced]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: do_nothing
    opponents: [mushroom_war_passive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: do_nothing
    opponents: [mushroom_war_slimy]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Mushroom War
    agent: mushroom_war_aggressive
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_aggressive
    opponents: [mushroom_war_aggressive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_aggressive
    opponents: [mushroom_war_balanced]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_aggressive
    opponents: [mushroom_war_passive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_aggressive
    opponents: [mushroom_war_slimy]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Mushroom War
    agent: mushroom_war_balanced
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_balanced
    opponents: [mushroom_war_aggressive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_balanced
    opponents: [mushroom_war_balanced]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_balanced
    opponents: [mushroom_war_passive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_balanced
    opponents: [mushroom_war_slimy]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Mushroom War
    agent: mushroom_war_passive
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_passive
    opponents: [mushroom_war_aggressive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_passive
    opponents: [mushroom_war_balanced]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_passive
    opponents: [mushroom_war_passive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_passive
    opponents: [mushroom_war_slimy]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Mushroom War
    agent: mushroom_war_slimy
    opponents: [do_nothing]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_slimy
    opponents: [mushroom_war_aggressive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_slimy
    opponents: [mushroom_war_balanced]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_slimy
    opponents: [mushroom_war_passive]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
  - name: Mushroom War
    agent: mushroom_war_slimy
    opponents: [mushroom_war_slimy]
    num_episodes: 20
    kwargs:
      episode_timeout: 120


hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}