defaults:
  - _self_
  - agents:
    - tacticrafter

mc_port: 49172
server_port: 3000
env_wait_ticks: 80

scenarios:
#   E
  - name: Mushroom War
    agent: tacticrafter
    opponents: [tacticrafter]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: tacticrafter
    opponents: [tacticrafter]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Mushroom War
    agent: tacticrafter
    opponents: [tacticrafter]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: tacticrafter
    opponents: [tacticrafter]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Mushroom War
    agent: tacticrafter
    opponents: [tacticrafter]
    num_episodes: 20
    kwargs:
      episode_timeout: 120
#   E
  - name: Dash and Dine
    agent: tacticrafter
    opponents: [tacticrafter]
    num_episodes: 20
    kwargs:
      episode_timeout: 120


hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}